name: Sync

on:
  schedule:
     - cron: '0 0 * * *'
  push:
    tags:
      - 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set a variable
        run: echo "::set-output name=myTime::$(date +'%Y-%m-%d %H:%M:%S')"
        id: myStep
        
      - uses: actions/checkout@v2
        name: Checkout
      - name: Download file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERID }}
          insecure_password: ${{ secrets.FTP_PASSWORD }}
          source: ${{ secrets.FTP_PATH }}
          insecure_ignore_fingerprint: true
          target: ..
    
    # 커밋
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0
        with:
          add: '.'
          ref: "main"
          author_name: 'Piorosen-Bot'
          author_email: 'ckwngud1@gmail.com'
          message: "[BOT] update submodule [ ${{ steps.myStep.outputs.myTime }} ]"
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        
    # 푸시
      - name: Push commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          repository: eunjae-farm/yongcart5
          branch: main
