name: Sync

on:
  schedule:
     - cron: '0 0 * * *'
  push:
    tags:
      - 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set a variable
        run: echo "::set-output name=myTime::$(date +'%Y-%m-%d %H:%M:%S')"
        id: myStep
        
      - uses: actions/checkout@v2
        name: Checkout

      - name: make deploy keys
        env:
          GH_ACTION_DEPLOY_KEY: ${{ secrets.GIT_SSH }}
        run: |
          mkdir -p ~/.ssh/
          echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Run Bootstrap Script
        shell: bash
        run: |
         ls
         pwd
         sudo apt install -y git sshpass openssh-server
         rm -rf *
         echo '${{ secrets.FTP_PASSWORD }}' > pass_file
         sudo sshpass -f pass_file scp -o StrictHostKeyChecking=no -r ${{ secrets.FTP_USERID }}@${{ secrets.FTP_HOST }}:${{ secrets.FTP_PATH }} ..
         sudo cp -r ../www/* ./
         
    # 커밋
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0
        with:
          add: '.'
          ref: "main"
          author_name: 'Piorosen-Bot'
          author_email: 'ckwngud1@gmail.com'
          message: "[BOT] update submodule [ ${{ steps.myStep.outputs.myTime }} ]"
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        
    # 푸시
      - name: Push commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          repository: eunjae-farm/yongcart5
          branch: main
